/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Operadora;
import javax.swing.JOptionPane;

/**
 *
 * @author DUARTE MENDEZ
 */
public class AñadirReceta extends javax.swing.JPanel {
    private Principal principal;
    private Operadora operadora;
    /**
     * Creates new form AñadirReceta
     */
    public AñadirReceta(Principal principal) {
        this.principal=principal;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        configusuario = new javax.swing.JButton();
        buscartxt = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        txtnombre = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        txtingredientes = new javax.swing.JLabel();
        ingredientes = new javax.swing.JTextField();
        txtpreparacion = new javax.swing.JLabel();
        preparacion = new javax.swing.JTextField();
        txtdescripcion = new javax.swing.JLabel();
        descripcion = new javax.swing.JTextField();
        txtcantidadpersonas = new javax.swing.JLabel();
        cantplatos = new javax.swing.JTextField();
        cancelar = new javax.swing.JButton();
        guardar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        marcaagua = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        configusuario.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        configusuario.setForeground(new java.awt.Color(0, 51, 153));
        configusuario.setText("Configurar usuario");
        configusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configusuarioActionPerformed(evt);
            }
        });
        add(configusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 280, -1));
        add(buscartxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(519, 10, 140, 40));

        buscar.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        buscar.setForeground(new java.awt.Color(0, 51, 153));
        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 120, 40));

        txtnombre.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        txtnombre.setForeground(new java.awt.Color(255, 153, 0));
        txtnombre.setText("Nombre");
        add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 90, -1));

        nombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 190, 30));

        txtingredientes.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        txtingredientes.setForeground(new java.awt.Color(255, 153, 0));
        txtingredientes.setText("Ingredientes");
        add(txtingredientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 150, -1));
        add(ingredientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 260, 70));

        txtpreparacion.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        txtpreparacion.setForeground(new java.awt.Color(255, 153, 0));
        txtpreparacion.setText("Preparacion");
        add(txtpreparacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 140, -1));
        add(preparacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 260, 60));

        txtdescripcion.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        txtdescripcion.setForeground(new java.awt.Color(255, 153, 0));
        txtdescripcion.setText("Descripcion");
        add(txtdescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 140, 30));
        add(descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 260, 80));

        txtcantidadpersonas.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        txtcantidadpersonas.setForeground(new java.awt.Color(255, 153, 0));
        txtcantidadpersonas.setText("Cantidad de personas");
        add(txtcantidadpersonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 470, 200, 50));

        cantplatos.setText("solo numeros");
        add(cantplatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 470, 210, 40));

        cancelar.setFont(new java.awt.Font("Sitka Text", 1, 11)); // NOI18N
        cancelar.setForeground(new java.awt.Color(0, 51, 153));
        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 540, 90, -1));

        guardar.setFont(new java.awt.Font("Sitka Text", 1, 11)); // NOI18N
        guardar.setForeground(new java.awt.Color(0, 51, 153));
        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        add(guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 540, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Nombre.png"))); // NOI18N
        jLabel1.setToolTipText("");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, -1, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Ingredientes.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 40, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Preparacion.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 40, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/descripcion.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 40, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Preparacion.png"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 40, 50));

        marcaagua.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 11)); // NOI18N
        marcaagua.setForeground(new java.awt.Color(255, 255, 255));
        marcaagua.setText("Easy Code");
        add(marcaagua, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 580, 80, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/fondo3.jpg"))); // NOI18N
        add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void configusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configusuarioActionPerformed
        configusu();
    }//GEN-LAST:event_configusuarioActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        volver();
    }//GEN-LAST:event_cancelarActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        guardar();
    }//GEN-LAST:event_guardarActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        busqueda();
    }//GEN-LAST:event_buscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscar;
    private javax.swing.JTextField buscartxt;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField cantplatos;
    private javax.swing.JButton configusuario;
    private javax.swing.JTextField descripcion;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton guardar;
    private javax.swing.JTextField ingredientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel marcaagua;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField preparacion;
    private javax.swing.JLabel txtcantidadpersonas;
    private javax.swing.JLabel txtdescripcion;
    private javax.swing.JLabel txtingredientes;
    private javax.swing.JLabel txtnombre;
    private javax.swing.JLabel txtpreparacion;
    // End of variables declaration//GEN-END:variables

    private void configusu() {
        principal.irConfigcuenta(this);
    }

    private void volver() {
        principal.irmenu(this);
    }
    private void busqueda() {
        this.operadora=new Operadora();
        int p;
        if(buscartxt.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Lo sentimos no has escrito un nombre");
        }else{
            p=operadora.getLogica().buscarReceta(operadora.getLogica().ubicacionDeUsuarioPorIndice(principal.getUsuariotem()), buscartxt.getText());
            if(-1 == p){
                JOptionPane.showMessageDialog(null, "no existe");
            }else{
                principal.setUbicacion(p);
                principal.setNombrerec(buscartxt.getText());
                principal.irMostrarReceta(this);
            }
        }
        
    }
    private void guardar() {
        this.operadora=new Operadora();
        if(nombre.getText().equals("") || ingredientes.getText().equals("") || preparacion.getText().equals("") || descripcion.getText().equals("") || cantplatos.getText().equals("solo numeros")){
            JOptionPane.showMessageDialog(null, "Tienes alguna casilla vacia");
        }else{
            int platos= Integer.parseInt(cantplatos.getText());
            if(operadora.getLogica().validarNuevaReceta(operadora.getLogica().ubicacionDeUsuarioPorIndice(principal.getUsuariotem()), nombre.getText(), ingredientes.getText(), preparacion.getText(), descripcion.getText(), platos)){
                JOptionPane.showMessageDialog(null, "Guardada con exito");
                nombre.setText("");
                ingredientes.setText("");
                preparacion.setText("");
                descripcion.setText("");
                cantplatos.setText("");
            }else{
                JOptionPane.showMessageDialog(null, "Upss Ah ocurrido un error");
            }
        }
    }
}
