/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author DUARTE MENDEZ
 */
public class Iniciosesion extends javax.swing.JPanel {
    private Principal principal;
    /**
     * Creates new form Iniciosesion
     */
    public Iniciosesion(Principal principal) {
        this.principal=principal;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inidsesi = new javax.swing.JLabel();
        Olvicontra = new javax.swing.JLabel();
        marcaagua = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        contraseña = new javax.swing.JPasswordField();
        logear = new javax.swing.JButton();
        registrar = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inidsesi.setFont(new java.awt.Font("Sitka Text", 1, 48)); // NOI18N
        inidsesi.setForeground(new java.awt.Color(255, 255, 255));
        inidsesi.setText("Inicio De Sesión");
        add(inidsesi, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 520, 80));

        Olvicontra.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        Olvicontra.setForeground(new java.awt.Color(255, 255, 255));
        Olvicontra.setText("Olvido su contraseña");
        Olvicontra.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                OlvicontraAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        Olvicontra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OlvicontraMouseClicked(evt);
            }
        });
        add(Olvicontra, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 240, 30));

        marcaagua.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 11)); // NOI18N
        marcaagua.setForeground(new java.awt.Color(255, 255, 255));
        marcaagua.setText("Easy Code");
        add(marcaagua, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 580, 80, -1));

        jLabel1.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuario");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 130, 20));
        add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 170, -1));

        jLabel2.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Contraseña");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 130, -1));
        add(contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 170, -1));

        logear.setBackground(new java.awt.Color(204, 0, 51));
        logear.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        logear.setForeground(new java.awt.Color(102, 204, 0));
        logear.setText("Aceptar");
        logear.setPreferredSize(new java.awt.Dimension(87, 23));
        logear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logearActionPerformed(evt);
            }
        });
        add(logear, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 353, 100, 30));

        registrar.setBackground(new java.awt.Color(204, 0, 51));
        registrar.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        registrar.setForeground(new java.awt.Color(102, 204, 0));
        registrar.setText("Registrarse");
        registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarActionPerformed(evt);
            }
        });
        add(registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 353, -1, 30));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/fondo.jpg"))); // NOI18N
        fondo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void OlvicontraAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_OlvicontraAncestorAdded
        
    }//GEN-LAST:event_OlvicontraAncestorAdded

    private void logearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logearActionPerformed
        entrar();       
    }//GEN-LAST:event_logearActionPerformed

    private void registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarActionPerformed
        registrar();
    }//GEN-LAST:event_registrarActionPerformed

    private void OlvicontraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OlvicontraMouseClicked
        recupera();
    }//GEN-LAST:event_OlvicontraMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Olvicontra;
    private javax.swing.JPasswordField contraseña;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel inidsesi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton logear;
    private javax.swing.JLabel marcaagua;
    private javax.swing.JButton registrar;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables

    private void entrar() {
        
        principal.irmenu(this);
    }

    private void registrar() {
        principal.irRegistrar(this);
    }

    private void recupera() {
        principal.irRecuperacuenta(this);
    }
}
