/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Operadora;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author DUARTE MENDEZ
 */
public class Menu1 extends javax.swing.JPanel {
    private Operadora operadora;
    private Principal principal;
    /**
     * Creates new form Menu1
     */
    public Menu1(Principal principal) {
        this.principal=principal;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        image1 = new javax.swing.JLabel();
        image2 = new javax.swing.JLabel();
        image3 = new javax.swing.JLabel();
        image4 = new javax.swing.JLabel();
        añadirre = new javax.swing.JButton();
        buscar = new javax.swing.JButton();
        buscador = new javax.swing.JTextField();
        misrecetas = new javax.swing.JButton();
        recetas = new javax.swing.JButton();
        configusuario = new javax.swing.JButton();
        cerrarsesion = new javax.swing.JButton();
        tips = new javax.swing.JButton();
        marcaagua = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        image1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagen 1.jpg"))); // NOI18N
        add(image1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, -1));

        image2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagen2.jpg"))); // NOI18N
        image2.setToolTipText("");
        add(image2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, -1, -1));

        image3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagen3.jpg"))); // NOI18N
        add(image3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, -1, -1));

        image4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagen4.jpg"))); // NOI18N
        add(image4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 60, -1, -1));

        añadirre.setBackground(new java.awt.Color(153, 153, 153));
        añadirre.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        añadirre.setForeground(new java.awt.Color(0, 51, 102));
        añadirre.setText("AÑADIR RECETAS");
        añadirre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirreActionPerformed(evt);
            }
        });
        add(añadirre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 280, 100));

        buscar.setBackground(new java.awt.Color(153, 153, 153));
        buscar.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        buscar.setForeground(new java.awt.Color(0, 51, 102));
        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 120, 40));

        buscador.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buscador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buscadorKeyPressed(evt);
            }
        });
        add(buscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(519, 10, 140, 40));

        misrecetas.setBackground(new java.awt.Color(153, 153, 153));
        misrecetas.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        misrecetas.setForeground(new java.awt.Color(0, 51, 102));
        misrecetas.setText("MIS RECETAS");
        misrecetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                misrecetasActionPerformed(evt);
            }
        });
        add(misrecetas, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, 280, 100));

        recetas.setBackground(new java.awt.Color(153, 153, 153));
        recetas.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        recetas.setForeground(new java.awt.Color(0, 51, 102));
        recetas.setText("RECETAS");
        recetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recetasActionPerformed(evt);
            }
        });
        add(recetas, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 280, 100));

        configusuario.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        configusuario.setForeground(new java.awt.Color(0, 51, 102));
        configusuario.setText("Configurar usuario");
        configusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configusuarioActionPerformed(evt);
            }
        });
        add(configusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 300, -1));

        cerrarsesion.setBackground(new java.awt.Color(153, 153, 153));
        cerrarsesion.setFont(new java.awt.Font("Sitka Text", 1, 11)); // NOI18N
        cerrarsesion.setForeground(new java.awt.Color(0, 51, 102));
        cerrarsesion.setText("Cerrar Sesion");
        cerrarsesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarsesionActionPerformed(evt);
            }
        });
        add(cerrarsesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(623, 553, 160, 30));

        tips.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        tips.setForeground(new java.awt.Color(0, 51, 102));
        tips.setText("TIPS PARA COCINAR");
        tips.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipsActionPerformed(evt);
            }
        });
        add(tips, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 280, 90));

        marcaagua.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 11)); // NOI18N
        marcaagua.setForeground(new java.awt.Color(255, 255, 255));
        marcaagua.setText("Easy Code");
        add(marcaagua, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 580, 80, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Fondo2.png"))); // NOI18N
        add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void misrecetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_misrecetasActionPerformed
        misrecetas();
    }//GEN-LAST:event_misrecetasActionPerformed

    private void cerrarsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarsesionActionPerformed
        salir();
    }//GEN-LAST:event_cerrarsesionActionPerformed

    private void añadirreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadirreActionPerformed
        añadirrec();
    }//GEN-LAST:event_añadirreActionPerformed

    private void configusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configusuarioActionPerformed
        configusu();
    }//GEN-LAST:event_configusuarioActionPerformed

    private void recetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recetasActionPerformed
        recetas();
    }//GEN-LAST:event_recetasActionPerformed

    private void tipsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipsActionPerformed
        tips();
    }//GEN-LAST:event_tipsActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        busqueda();
    }//GEN-LAST:event_buscarActionPerformed

    private void buscadorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscadorKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER) busqueda();
    }//GEN-LAST:event_buscadorKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton añadirre;
    private javax.swing.JTextField buscador;
    private javax.swing.JButton buscar;
    private javax.swing.JButton cerrarsesion;
    private javax.swing.JButton configusuario;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel image1;
    private javax.swing.JLabel image2;
    private javax.swing.JLabel image3;
    private javax.swing.JLabel image4;
    private javax.swing.JLabel marcaagua;
    private javax.swing.JButton misrecetas;
    private javax.swing.JButton recetas;
    private javax.swing.JButton tips;
    // End of variables declaration//GEN-END:variables

    private void salir() {
        principal.iriniciars(this);
    }
    private void busqueda() {
        this.operadora=new Operadora();
        int p,j;
        if(buscador.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Lo sentimos no has escrito un nombre");
        }else{
            p=operadora.getLogica().buscarReceta(principal.getUsuariotem(), buscador.getText());
            j=operadora.getLogica().buscarrecetapersona(principal.getUsuariotem(), buscador.getText());
            if(-1 == p && -1==j){
                JOptionPane.showMessageDialog(null, "no existe");
            }else{
                if(p!=-1){
                    principal.settipo("alcatraz");
                    principal.setUbicacion(p);
                }else if(j!=1){
                    principal.settipo("otro");
                    principal.setUbicacion(j);
                }
                principal.setNombrerec(buscador.getText());
                principal.irMostrarReceta(this);
            }
        }
        
    }
    private void añadirrec() {
        principal.irAñadirreceta(this);
    }

    private void configusu() {
        principal.irConfigcuenta(this);
    }

    private void recetas() {
        principal.irRecetas(this);
    }

    private void misrecetas() {
        principal.irMisRecetas(this);
    }
    private void tips() {
        principal.irTips(this);
    }
}
