/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Operadora;
import java.util.ArrayList;
import modelo.Receta;

/**
 *
 * @author DUARTE MENDEZ
 */
public class MostrarReceta extends javax.swing.JPanel {
    private Principal principal;
    private Operadora operadora;
    /**
     * Creates new form MostrarReceta
     */
    public MostrarReceta(Principal principal) {
        this.operadora=new Operadora();
        this.principal=principal;
        String nombr= principal.getNombrerec();
        
        ArrayList<Receta> listaRecetas;
        initComponents();
        System.out.println(operadora.getLogica().verResultadoBusqueda(operadora.getLogica().ubicacionDeUsuarioPorIndice(principal.getUsuariotem()), principal.getUbicacion()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tips = new javax.swing.JButton();
        misrecetas = new javax.swing.JButton();
        recetas = new javax.swing.JButton();
        menu = new javax.swing.JButton();
        editarreceta = new javax.swing.JButton();
        añadirrecetas = new javax.swing.JButton();
        nombre = new javax.swing.JLabel();
        ingredientes = new javax.swing.JLabel();
        preparacion = new javax.swing.JLabel();
        descripcion = new javax.swing.JLabel();
        cantidadplatos = new javax.swing.JLabel();
        titulo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tips.setBackground(new java.awt.Color(255, 204, 0));
        tips.setFont(new java.awt.Font("Sitka Text", 1, 11)); // NOI18N
        tips.setForeground(new java.awt.Color(0, 51, 153));
        tips.setText("tips");
        tips.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipsActionPerformed(evt);
            }
        });
        add(tips, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 340, 110, -1));

        misrecetas.setBackground(new java.awt.Color(255, 204, 0));
        misrecetas.setFont(new java.awt.Font("Sitka Text", 1, 11)); // NOI18N
        misrecetas.setForeground(new java.awt.Color(0, 51, 153));
        misrecetas.setText("MisRecetas");
        misrecetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                misrecetasActionPerformed(evt);
            }
        });
        add(misrecetas, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 380, 110, -1));

        recetas.setBackground(new java.awt.Color(255, 204, 0));
        recetas.setFont(new java.awt.Font("Sitka Text", 1, 11)); // NOI18N
        recetas.setForeground(new java.awt.Color(0, 51, 153));
        recetas.setText("Recetas");
        recetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recetasActionPerformed(evt);
            }
        });
        add(recetas, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 420, 110, -1));

        menu.setBackground(new java.awt.Color(255, 204, 0));
        menu.setFont(new java.awt.Font("Sitka Text", 1, 11)); // NOI18N
        menu.setForeground(new java.awt.Color(0, 51, 153));
        menu.setText("Menu");
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });
        add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 460, 110, -1));

        editarreceta.setBackground(new java.awt.Color(255, 204, 0));
        editarreceta.setFont(new java.awt.Font("Sitka Text", 1, 11)); // NOI18N
        editarreceta.setForeground(new java.awt.Color(0, 51, 153));
        editarreceta.setText("EditarReceta");
        editarreceta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarrecetaActionPerformed(evt);
            }
        });
        add(editarreceta, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 500, 110, -1));

        añadirrecetas.setBackground(new java.awt.Color(255, 204, 0));
        añadirrecetas.setFont(new java.awt.Font("Sitka Text", 1, 11)); // NOI18N
        añadirrecetas.setForeground(new java.awt.Color(0, 51, 153));
        añadirrecetas.setText("AñadirReceta");
        añadirrecetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirrecetasActionPerformed(evt);
            }
        });
        add(añadirrecetas, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 540, 110, -1));

        nombre.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nombre.setText("titulo");
        add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 80, 40));

        ingredientes.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        ingredientes.setText("ingredts");
        add(ingredientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 600, 70));

        preparacion.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        preparacion.setText("preparacion");
        add(preparacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 600, 70));

        descripcion.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        descripcion.setText("descripcion");
        add(descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 309, 600, 60));

        cantidadplatos.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        cantidadplatos.setText("cantidad de platos");
        add(cantidadplatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 150, 60));
        add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 190, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Fondotenue22.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void tipsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipsActionPerformed
        tips();
    }//GEN-LAST:event_tipsActionPerformed

    private void misrecetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_misrecetasActionPerformed
        mrecetas();
    }//GEN-LAST:event_misrecetasActionPerformed

    private void recetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recetasActionPerformed
        recetas();
    }//GEN-LAST:event_recetasActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        menu();
    }//GEN-LAST:event_menuActionPerformed

    private void editarrecetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarrecetaActionPerformed
        erecetas();
    }//GEN-LAST:event_editarrecetaActionPerformed

    private void añadirrecetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadirrecetasActionPerformed
        arecetas();
    }//GEN-LAST:event_añadirrecetasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton añadirrecetas;
    private javax.swing.JLabel cantidadplatos;
    private javax.swing.JLabel descripcion;
    private javax.swing.JButton editarreceta;
    private javax.swing.JLabel ingredientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton menu;
    private javax.swing.JButton misrecetas;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel preparacion;
    private javax.swing.JButton recetas;
    private javax.swing.JButton tips;
    private javax.swing.JTextField titulo;
    // End of variables declaration//GEN-END:variables

    private void tips() {
        principal.irTips(this);
    }

    private void mrecetas() {
        principal.irMisRecetas(this);
    }

    private void recetas() {
        principal.irRecetas(this);
    }

    private void menu() {
        principal.irmenu(this);
   }

    private void erecetas() {
        principal.irEditarReceta(this);
    }

    private void arecetas() {
        principal.irAñadirreceta(this);
    }
}
