/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Archivar;
import controlador.Operadora;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.Receta;

/**
 *
 * @author DUARTE MENDEZ
 */
public class MostrarReceta extends javax.swing.JPanel {
    protected Principal principal;
    private Archivar archivar;
    private Operadora operadora;
    /**
     * Creates new form MostrarReceta
     */
    public MostrarReceta(Principal principal) {
        this.principal= principal;
        this.operadora=new Operadora();
        this.archivar=new Archivar();
        ArrayList<Receta> receta= new ArrayList <Receta>();
        initComponents();
        System.out.println("principal ubicacion " +this.principal.getUbicacion() + "\nTipo que recibe:_ "+ operadora.getLogica().getResultadoss()+"\nusuario: "+ principal.getUsuariotem());
        if(principal.gettipo().equals("alcatraz")){
            archivar.traerRcetas("Admin");
        }else{
            archivar.traerRcetas(principal.getUsuariotem());
        }
        System.out.println("principal ubicacion " +principal.getUbicacion() + "\nUsuario:_ "+principal.gettipo());
        receta = archivar.getRecetasDeUsuario();
        nombre.setText(receta.get(principal.getUbicacion()).getNombre());
        ingredientes.setText(receta.get(principal.getUbicacion()).getIngredientes());
        ingredientes.enable(false);
        preparacion.setText(receta.get(principal.getUbicacion()).getPreparacion());
        preparacion.enable(false);
        descripcion.setText(receta.get(principal.getUbicacion()).getDescripcion());
        descripcion.enable(false);
        cantidadplatos.setText(Integer.toString(receta.get(principal.getUbicacion()).getCantidadDePersonas()));
        
            
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tips = new javax.swing.JButton();
        misrecetas = new javax.swing.JButton();
        recetas = new javax.swing.JButton();
        menu = new javax.swing.JButton();
        añadirrecetas = new javax.swing.JButton();
        nombre = new javax.swing.JLabel();
        cantidadplatos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ingredientes = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        preparacion = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        descripcion = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tips.setBackground(new java.awt.Color(255, 204, 0));
        tips.setFont(new java.awt.Font("Sitka Text", 1, 11)); // NOI18N
        tips.setForeground(new java.awt.Color(0, 51, 153));
        tips.setText("tips");
        tips.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipsActionPerformed(evt);
            }
        });
        add(tips, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 340, 110, -1));

        misrecetas.setBackground(new java.awt.Color(255, 204, 0));
        misrecetas.setFont(new java.awt.Font("Sitka Text", 1, 11)); // NOI18N
        misrecetas.setForeground(new java.awt.Color(0, 51, 153));
        misrecetas.setText("MisRecetas");
        misrecetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                misrecetasActionPerformed(evt);
            }
        });
        add(misrecetas, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 390, 110, -1));

        recetas.setBackground(new java.awt.Color(255, 204, 0));
        recetas.setFont(new java.awt.Font("Sitka Text", 1, 11)); // NOI18N
        recetas.setForeground(new java.awt.Color(0, 51, 153));
        recetas.setText("Recetas");
        recetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recetasActionPerformed(evt);
            }
        });
        add(recetas, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 440, 110, -1));

        menu.setBackground(new java.awt.Color(255, 204, 0));
        menu.setFont(new java.awt.Font("Sitka Text", 1, 11)); // NOI18N
        menu.setForeground(new java.awt.Color(0, 51, 153));
        menu.setText("Menu");
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });
        add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 490, 110, -1));

        añadirrecetas.setBackground(new java.awt.Color(255, 204, 0));
        añadirrecetas.setFont(new java.awt.Font("Sitka Text", 1, 11)); // NOI18N
        añadirrecetas.setForeground(new java.awt.Color(0, 51, 153));
        añadirrecetas.setText("AñadirReceta");
        añadirrecetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirrecetasActionPerformed(evt);
            }
        });
        add(añadirrecetas, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 540, 110, -1));

        nombre.setFont(new java.awt.Font("Sitka Text", 1, 36)); // NOI18N
        add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 40, 530, 40));

        cantidadplatos.setFont(new java.awt.Font("Sitka Text", 1, 36)); // NOI18N
        add(cantidadplatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, 210, 60));

        ingredientes.setBackground(new java.awt.Color(240, 240, 240));
        ingredientes.setColumns(1);
        ingredientes.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        ingredientes.setForeground(new java.awt.Color(240, 240, 240));
        ingredientes.setRows(5);
        jScrollPane1.setViewportView(ingredientes);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 750, 80));

        preparacion.setBackground(new java.awt.Color(240, 240, 240));
        preparacion.setColumns(20);
        preparacion.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        preparacion.setForeground(new java.awt.Color(240, 240, 240));
        preparacion.setRows(5);
        jScrollPane2.setViewportView(preparacion);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 750, 90));

        descripcion.setBackground(new java.awt.Color(240, 240, 240));
        descripcion.setColumns(20);
        descripcion.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        descripcion.setForeground(new java.awt.Color(240, 240, 240));
        descripcion.setRows(5);
        jScrollPane3.setViewportView(descripcion);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 620, 110));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Fondotenue22.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void tipsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipsActionPerformed
        tips();
    }//GEN-LAST:event_tipsActionPerformed

    private void misrecetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_misrecetasActionPerformed
        mrecetas();
    }//GEN-LAST:event_misrecetasActionPerformed

    private void recetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recetasActionPerformed
        recetas();
    }//GEN-LAST:event_recetasActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        menu();
    }//GEN-LAST:event_menuActionPerformed

    private void añadirrecetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadirrecetasActionPerformed
        arecetas();
    }//GEN-LAST:event_añadirrecetasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton añadirrecetas;
    private javax.swing.JLabel cantidadplatos;
    private javax.swing.JTextArea descripcion;
    private javax.swing.JTextArea ingredientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton menu;
    private javax.swing.JButton misrecetas;
    private javax.swing.JLabel nombre;
    private javax.swing.JTextArea preparacion;
    private javax.swing.JButton recetas;
    private javax.swing.JButton tips;
    // End of variables declaration//GEN-END:variables

    private void tips() {
        principal.irTips(this);
    }

    private void mrecetas() {
        principal.irMisRecetas(this);
    }

    private void recetas() {
        principal.irRecetas(this);
    }

    private void menu() {
        principal.irmenu(this);
   }


    private void arecetas() {
        principal.irAñadirreceta(this);
    }
}
