/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Operadora;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DUARTE MENDEZ
 */
public class Recetas extends javax.swing.JPanel {
    DefaultTableModel modelo;
    Principal principal;
    private Operadora operadora;
    /**
     * Creates new form Recetas
     */
    public Recetas(Principal principal) {
        this.principal=principal;
        initComponents();
        modelo= new DefaultTableModel();
        modelo.addColumn("Nombre");
        modelo.addColumn("descripcion");
        this.jTable1.setModel(modelo);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        configusuario = new javax.swing.JButton();
        buscador = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        cerrarsesion = new javax.swing.JButton();
        recetas = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        volver = new javax.swing.JButton();
        misrecetas = new javax.swing.JButton();
        marcaagua = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        configusuario.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        configusuario.setForeground(new java.awt.Color(0, 51, 102));
        configusuario.setText("Configurar usuario");
        configusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configusuarioActionPerformed(evt);
            }
        });
        add(configusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 300, -1));

        buscador.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(buscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(519, 10, 140, 40));

        buscar.setBackground(new java.awt.Color(153, 153, 153));
        buscar.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        buscar.setForeground(new java.awt.Color(0, 51, 102));
        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 120, 40));

        cerrarsesion.setBackground(new java.awt.Color(153, 153, 153));
        cerrarsesion.setFont(new java.awt.Font("Sitka Text", 1, 11)); // NOI18N
        cerrarsesion.setForeground(new java.awt.Color(0, 51, 102));
        cerrarsesion.setText("Cerrar Sesion");
        cerrarsesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarsesionActionPerformed(evt);
            }
        });
        add(cerrarsesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(623, 553, 160, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        recetas.setViewportView(jTable1);

        add(recetas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 710, -1));

        volver.setFont(new java.awt.Font("Sitka Text", 1, 11)); // NOI18N
        volver.setForeground(new java.awt.Color(0, 51, 102));
        volver.setText("Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 550, 160, 30));

        misrecetas.setFont(new java.awt.Font("Sitka Text", 1, 11)); // NOI18N
        misrecetas.setForeground(new java.awt.Color(0, 51, 102));
        misrecetas.setText("Mis recetas");
        misrecetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                misrecetasActionPerformed(evt);
            }
        });
        add(misrecetas, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 550, 160, 30));

        marcaagua.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 11)); // NOI18N
        marcaagua.setForeground(new java.awt.Color(255, 255, 255));
        marcaagua.setText("Easy Code");
        add(marcaagua, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 580, 80, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Fondo2.png"))); // NOI18N
        add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void configusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configusuarioActionPerformed
        configusu();
    }//GEN-LAST:event_configusuarioActionPerformed

    private void cerrarsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarsesionActionPerformed
        salir();
    }//GEN-LAST:event_cerrarsesionActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        volver();
    }//GEN-LAST:event_volverActionPerformed

    private void misrecetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_misrecetasActionPerformed
        misrecetas();
    }//GEN-LAST:event_misrecetasActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        busqueda();
    }//GEN-LAST:event_buscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField buscador;
    private javax.swing.JButton buscar;
    private javax.swing.JButton cerrarsesion;
    private javax.swing.JButton configusuario;
    private javax.swing.JLabel fondo;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel marcaagua;
    private javax.swing.JButton misrecetas;
    private javax.swing.JScrollPane recetas;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables

    private void configusu() {
        principal.irConfigcuenta(this);
    }
    private void busqueda() {
        this.operadora=new Operadora();
        int p;
        if(buscador.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Lo sentimos no has escrito un nombre");
        }else{
            p=operadora.getLogica().buscarReceta(operadora.getLogica().ubicacionDeUsuarioPorIndice(principal.getUsuariotem()), buscador.getText());
            if(-1 == p){
                JOptionPane.showMessageDialog(null, "no existe");
            }else{
                principal.setUbicacion(p);
                principal.setNombrerec(buscador.getText());
                principal.irMostrarReceta(this);
            }
        }
        
    }
    private void salir() {
        principal.iriniciars(this);
    }

    private void volver() {
        principal.irmenu(this);
    }

    private void misrecetas() {
        principal.irMisRecetas(this);
    }
}
