/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Operadora;
import javax.swing.JOptionPane;

/**
 *
 * @author DUARTE MENDEZ
 */
public class Registrarse extends javax.swing.JPanel {
    private Principal principal;
    private Operadora operadora;
    /**
     * Creates new form registrarse
     */
    public Registrarse(Principal principal) {
        this.principal=principal;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        regis = new javax.swing.JLabel();
        usuatext = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        contratext = new javax.swing.JLabel();
        contraseña = new javax.swing.JPasswordField();
        confirmar = new javax.swing.JLabel();
        contraconftext = new javax.swing.JLabel();
        confirmacont = new javax.swing.JPasswordField();
        pal = new javax.swing.JLabel();
        recu = new javax.swing.JLabel();
        palabrarecuperacion = new javax.swing.JTextField();
        aceptar = new javax.swing.JButton();
        regresar = new javax.swing.JButton();
        marcaagua = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        regis.setFont(new java.awt.Font("Sitka Text", 1, 48)); // NOI18N
        regis.setForeground(new java.awt.Color(255, 255, 255));
        regis.setText("Registrarse");
        add(regis, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 370, 100));

        usuatext.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        usuatext.setForeground(new java.awt.Color(255, 255, 255));
        usuatext.setText("Usuario");
        add(usuatext, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 70, -1));
        add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 210, -1));

        contratext.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        contratext.setForeground(new java.awt.Color(255, 255, 255));
        contratext.setText("Contraseña");
        add(contratext, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 120, -1));

        contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraseñaActionPerformed(evt);
            }
        });
        add(contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 210, -1));

        confirmar.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        confirmar.setForeground(new java.awt.Color(255, 255, 255));
        confirmar.setText("Confirmar");
        confirmar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(confirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 100, 30));

        contraconftext.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        contraconftext.setForeground(new java.awt.Color(255, 255, 255));
        contraconftext.setText("Contraseña");
        add(contraconftext, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 120, 30));

        confirmacont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmacontActionPerformed(evt);
            }
        });
        add(confirmacont, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 210, -1));

        pal.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        pal.setForeground(new java.awt.Color(255, 255, 255));
        pal.setText("Palabra De");
        add(pal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, 20));

        recu.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        recu.setForeground(new java.awt.Color(255, 255, 255));
        recu.setText("Recuperacion");
        add(recu, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 130, 20));
        add(palabrarecuperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, 210, -1));

        aceptar.setBackground(new java.awt.Color(204, 0, 51));
        aceptar.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        aceptar.setForeground(new java.awt.Color(102, 204, 0));
        aceptar.setText("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });
        add(aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 473, 110, 30));

        regresar.setBackground(new java.awt.Color(204, 0, 51));
        regresar.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        regresar.setForeground(new java.awt.Color(102, 204, 0));
        regresar.setText("Volver");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });
        add(regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 473, 110, 30));

        marcaagua.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 11)); // NOI18N
        marcaagua.setForeground(new java.awt.Color(255, 255, 255));
        marcaagua.setText("Easy Code");
        add(marcaagua, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 580, 80, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/fondo.jpg"))); // NOI18N
        add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void contraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contraseñaActionPerformed

    private void confirmacontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmacontActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmacontActionPerformed

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        verificar();
    }//GEN-LAST:event_aceptarActionPerformed

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        volver();
    }//GEN-LAST:event_regresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JPasswordField confirmacont;
    private javax.swing.JLabel confirmar;
    private javax.swing.JLabel contraconftext;
    private javax.swing.JPasswordField contraseña;
    private javax.swing.JLabel contratext;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel marcaagua;
    private javax.swing.JLabel pal;
    private javax.swing.JTextField palabrarecuperacion;
    private javax.swing.JLabel recu;
    private javax.swing.JLabel regis;
    private javax.swing.JButton regresar;
    private javax.swing.JTextField usuario;
    private javax.swing.JLabel usuatext;
    // End of variables declaration//GEN-END:variables

    private void volver() {
        principal.iriniciars(this);
    }

    private void verificar() {
        this.operadora = new Operadora();
        if(usuario.getText().equals("") || contraseña.getText().equals("") || confirmacont.getText().equals("") || palabrarecuperacion.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Falta algun espacio por llenar");
        }else{
            switch(operadora.getLogica().ValidarRegistro(usuario.getText(), contraseña.getText(), confirmacont.getText(), palabrarecuperacion.getText())){
                case 0:
                    JOptionPane.showMessageDialog(null, "Cargado con exito");
                    principal.iriniciars(this);
                    break;
                case 1:
                    JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden");
                    break;
                case 2:
                    JOptionPane.showMessageDialog(null, "Usuario ya existe");
                    break;
                default:
                    JOptionPane.showMessageDialog(null, "error manin");
                    break;
            }
                    
        }
        
    }
}
